---
title: "\"Homework 3 Task 2 - Hierarchical Clustering"
author: "Matthieu Huy"
date: "2023-02-26"
output: html_document
---

```{r setup, echo = TRUE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(here)

# Packages for cluster analysis:

library(NbClust)
library(cluster)
library(factoextra)
library(dendextend)
library(ggdendro)
```

### Read in data and deal with NA values

```{r}
stream_data <- read_csv(here("data/sbc_lter_registered_stream_chemistry.csv")) |>
  clean_names()

summary(stream_data) 
#tpc_u_m, tpn_u_m, tpp_u_m, and tss_mgper_liter columns have median = -999
#indicating >50% of col is NA

stream_data[stream_data== -999] <- NA #replace all -999 values with NA

colSums(is.na(stream_data)) 
#cols [td_u_m:tss_mgper_liter] have > 5000, or 25% of values as NA

```

For the purpose of this analysis, we will use a 50% threshold to remove columns with a lot of NA values from our data, assuming that these variables are not statistically important. 

```{r}
stream_means <- stream_data |>
  select(-c(tpc_u_m:tss_mgper_liter)) |> #exclude cols where >50% of values are NA
  group_by(site_code) |>
  summarise_at(vars(-timestamp_local), c(mean = "mean"), na.rm = TRUE)

### summary(stream_data) shows that we need to scale data

stream_scaled <- stream_means |>
  select(where(is.numeric)) |>
  scale()

rownames(stream_scaled) <- stream_means$site_code

# summary(stream_scaled)
```

```{r}
### Compute Euclidean distances:
euc_distance <- dist(stream_scaled, 
                     method = "euclidean") ### add diag and upper

### Check out the output:
# euc_distance
```

```{r}
# Hierarchical clustering (complete linkage)
hc_complete <- hclust(euc_distance, method = "complete" )

# Plot:
ggdendrogram(hc_complete, 
             rotate = FALSE) +
  theme_minimal() +
  labs(x = "Site Code")
# y - euclidian distance
# COOL. Then you can customize w/ usual ggplot tools. 
```

### Notes 

- Need to add caption to plot
- Need to provide explanation/analysis summary
